import {collection,doc,onSnapshot,runTransaction,type Firestore} from 'firebase/firestore';
import {button,element,field,input} from './dom';
import {sharedEditor} from './shared-editor';
import {validateSetlist,type Setlist} from './setlists';
import {safeURL,type Song} from './repertoire';
export function mountSetlists(db:Firestore,host:HTMLElement) {
  let songs:Song[]=[],ordered:string[]=[],targets:Record<string,string>={},ready=new Set<string>();
  const form=element('form',undefined,'panel setlist-editor'),title=input('text'),minutes=input('number'),notes=element('textarea'),target=element('select'),song=element('select'),order=element('ol');title.required=true;minutes.min='1';minutes.step='any';target.required=true;
  form.append(field('Nombre del setlist',title),field('Ensayo / concierto',target),field('Duración aproximada (minutos)',minutes),field('Notas musicales / interpretación',notes),field('Canción para añadir',song),button('Añadir canción al setlist',()=>{if(song.value){ordered.push(song.value);renderOrder();editor.markDirty();}}),order);
  function renderOrder(){order.replaceChildren();ordered.forEach((id,index)=>{const row=element('li'),name=songs.find(song=>song.id===id)?.title??'Canción no disponible';row.append(element('span',name));const up=button(`Subir ${name} (${index+1})`,()=>{[ordered[index-1],ordered[index]]=[ordered[index],ordered[index-1]];renderOrder();editor.markDirty();});up.disabled=index===0;up.dataset.unavailable=String(up.disabled);const down=button(`Bajar ${name} (${index+1})`,()=>{[ordered[index+1],ordered[index]]=[ordered[index],ordered[index+1]];renderOrder();editor.markDirty();});down.disabled=index===ordered.length-1;down.dataset.unavailable=String(down.disabled);row.append(up,down,button(`Quitar ${name} (${index+1})`,()=>{ordered.splice(index,1);renderOrder();editor.markDirty();}));order.append(row);});}
  function details(item:Setlist){const card=element('article',undefined,'panel');card.dataset.setlistDetails=item.id;card.append(element('h3',item.title),element('p',targets[`${item.targetType}/${item.targetId}`]??'Asociación no disponible'),element('p',item.minutes?`Duración aproximada: ${item.minutes} minutos`:'Duración sin especificar'),element('p',item.notes));const list=element('ol');for(const id of item.songIds){const song=songs.find(item=>item.id===id),row=element('li');row.append(element('span',song?`${song.title}${song.key?' · '+song.key:''}`:'Canción no disponible'));for(const resource of song?.resources??[]){try{const a=element('a',`${resource.kind}: ${resource.label}`);a.href=safeURL(resource.url);a.target='_blank';a.rel='noopener noreferrer';row.append(element('br'),a);}catch{row.append(element('p','Recurso con enlace no válido.'));}}list.append(row);}card.append(list);return card;}
  const editor=sharedEditor<Setlist>(db,host,'setlists','setlist',{form,ready:()=>ready.size===3,fill:item=>{title.value=item?.title??'';minutes.value=item?.minutes??'';notes.value=item?.notes??'';target.value=item?`${item.targetType}/${item.targetId}`:'';ordered=[...(item?.songIds??[])];renderOrder();},read:()=>{const [targetType,targetId]=target.value.split('/');return validateSetlist({title:title.value,minutes:minutes.value,notes:notes.value,songIds:ordered,targetType,targetId},songs.map(item=>item.id),Object.keys(targets));},details,save:async(id,revision,draft)=>{
    await runTransaction(db,async tx=>{const ref=doc(db,'setlists',id),record=await tx.get(ref);if((record.data()?.revision??0)!==revision)throw Error('shared-conflict');if(!(await tx.get(doc(db,draft.targetType,draft.targetId))).exists())throw Error('missing-target');for(const songId of new Set(draft.songIds))if(!(await tx.get(doc(db,'songs',songId))).exists())throw Error('missing-song');tx.set(ref,{...draft,revision:revision+1});});
  }});
  const targetRows:Record<string,Record<string,string>>={rehearsals:{},gigs:{}};
  const stops=['songs','rehearsals','gigs'].map(path=>onSnapshot(collection(db,path),{includeMetadataChanges:true},snapshot=>{
    if(snapshot.metadata.fromCache||snapshot.metadata.hasPendingWrites)return;
    if(path==='songs'){songs=snapshot.docs.map(row=>({...row.data(),id:row.id} as Song)).sort((a,b)=>a.title.localeCompare(b.title));const selected=song.value;song.replaceChildren();for(const item of songs){const option=element('option',item.title);option.value=item.id;song.append(option);}if(songs.some(item=>item.id===selected))song.value=selected;renderOrder();}
    else{targetRows[path]=Object.fromEntries(snapshot.docs.map(row=>[`${path}/${row.id}`,path==='gigs'?`Concierto: ${row.data().title}`:`Ensayo: ${row.data().date} · ${row.data().start} (Madrid)`]));targets={...targetRows.rehearsals,...targetRows.gigs};const selected=target.value;target.replaceChildren(element('option','Selecciona ensayo o concierto'));target.firstElementChild!.setAttribute('value','');for(const [id,name] of Object.entries(targets)){const option=element('option',name);option.value=id;target.append(option);}target.value=selected;}
    ready.add(path);editor.refresh();
  },()=>{ready.delete(path);editor.refresh();}));
  return ()=>{stops.forEach(stop=>stop());editor.dispose();};
}
